### ISSUE TITLE
Predict metadata (and tags)

### ISSUE THREAD

**Issue by zacchiro** [beancount/smart_importer#108]
I'm looking into switching from an import pipeline that relies on the mapping database of [icsv2ledger](https://github.com/quentinsf/icsv2ledger) (integrated into my importers) to smart_importer. The main shortcoming I'm seeing is that I cannot predict metadata or tags, unless I'm missing something.

As far as I can tell it should be possible to predict both, adding dedicated Predict* hooks.

Is that something that you'd be willing to consider, or is it out of scope for smart_importer ?

**Comment by zacchiro** [comment]
Ah, just found our past discussion in #34 :-) That's great as ground work. The question on whether you'd be willing to include this into smart_importer (e.g., if it's contributed as a patch/PR) is still valid though.

**Comment by tarioch** [comment]
I think in general smart importer is very open to contributions, so I don't see any problem with that and it fits nicely.

**Comment by johannesjh** [comment]
Hi, long time no update... shall we close this issue?
