### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by johannesjh** [beancount/smart_importer#41]
Thank you @tarioch for adding the examples folder. I would like to discuss ways of making the example more realistic and easier to understand for novice users. 

I think the example should illustrate the following usecase: Importing transactions from a debit or credit card, with automatic prediction of expense accounts:

- A realistic CSV file (`downloaded.csv` currently only consists of the word "test").
- The importer class should inherit from `beancount.ingest.importers.csv.Importer` and read the CSV file. There should be no hardcoded output in the importer class.
- I would like to use different account names that go together with the usecase of predicting expense categories. E.g., `Assets:MyBank:MyAccount`, `Assets:Cash`, `Expenses:Groceries`, `Expenses:Travel`...
- I think we should provide shorter and simpler training data in `example.beancount`. 

Any thoughts?

**Comment by varac** [comment]
Please improve examples and documentation, I am fighting for hours now how to get the smart_importer working with my own importer.

**Comment by johannesjh** [comment]
I currently reviewed the documentation... the "quickstart" section in the readme explains it quite well in my opinion. Not only does it provide an example, it also provides instructions for setting the whole thing up. I think I will close this issue.
