### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by johannesjh** [beancount/smart_importer#42]
in this branch: `feature/refs-42-improve-documentation`

**Comment by johannesjh** [comment]
I started working on the documentation in the branch `feature/refs-42-improve-documentation`. 

@tarioch : what do you think about the recommendation I gave, i.e., to apply the decorators to subclasses of importers in order to ease unittesting? That's how I have been using the smart_importers up until now.

Note: To keep things simple, I moved documentation regarding alternative ways applying the decorators to a separate file `docs/Applying_the_Decorators.rst`. I still need to figure out how link to this other file, I am new to the .rst syntax.

**Comment by tarioch** [comment]
I actually only use the smart importer in my import.config that way my importer code doesn't have any dependency on it and can be easily unit tested.

**Comment by varac** [comment]
Please improve examples and documentation, I am fighting for hours now how to get the smart_importer working with my own importer.

**Comment by johannesjh** [comment]
I quickly fixed some broken URLs in the documentation, and removed old obsolete plantuml diagram
https://github.com/beancount/smart_importer/pull/99

**Comment by johannesjh** [comment]
doc branch is merged. I will close this issue.
