### ISSUE TITLE
Option to use a mapping file along with regexs to over-ride or super seed smart importer suggestion

### ISSUE THREAD

**Issue by mondjef** [beancount/smart_importer#48]
This suggestion comes from a feature of icvs2legder (https://github.com/quentinsf/icsv2ledger) that I found very useful.  Basically it was a file that would contain descriptions mapped to both payee and account (comma separated values) that also allowed for the use of regular expressions.

To give you an example use case of how it can be used:
My preferred way to send and receive money with friends and family is via email money transfers.  My bank uses the following as the description when I receive one:  "ETF received Bob Smith".  For the posting I would like to see money going into the applicable bank account and coming out of the 'Accounts Receivable' for 'Bob Smith'....or any other name of person I receive one from.  To do this I would use a regex with a capture buffer that I can use to formulate the payee and account from.

**Comment by johannesjh** [comment]
That sounds like a nice feature. But I think that parsing CSV, mapping columns, and cleaning up data using regular expressions are all tasks that should be done in the importer classes, not in the machine learning decorators. For example, what you proposed could probably be implemented in a re-usable way as a mixin for `beancount.ingest.importers.csv.Importer`. I think that the main beancount repository would be be more suitable for an according pull request than this project.

-> I'd suggest to close this issue as I feel it is in the wrong place here.

**Comment by mondjef** [comment]
What you are proposing makes sense to me and would probably be a bit more flexible.  After thinking about it a bit more it might be over kill with the smart importer as in theory the user would only have to indicate the correct posting once and then the smarter importer should be able to then predict it moving forward.
