### ISSUE TITLE
Publish as Package on PyPI to ease installation

### ISSUE THREAD

**Issue by johannesjh** [beancount/smart_importer#51]
* [x] Read the Python packaging guide: https://packaging.python.org/tutorials/packaging-projects/#uploading-your-project-to-pypi
* [ ] Setup Makefile targets similar to fava, using [twine](https://pypi.org/project/twine/)
* [ ] Write a CHANGES file
* [ ] Set the initial version to 0.1.0 in `smart_importer/__init__.py`
* [ ] Tag v0.1.0 in git
* [ ] Create a release v0.1.0 in github
* [ ] Publish using twine on test.pypi.org and verify that it worked
* [ ] Publish using twine on production pypi.org
* [ ] Bump the version to 0.1.1-dev in `smart_importer/__init__.py`

**Comment by yagebu** [comment]
With setuptools_scm (#84), there's no need to bump versions and such, tagging is enough. I'll make a first release today.

**Comment by yagebu** [comment]
Done.

@johannesjh Let me know if I should add you as a maintainer on PyPI

**Comment by johannesjh** [comment]
Hi, thank you for publishing the package. And thank you for cleaning up the setup configuration, setuptools_scm looks very nice. If you could add me (account name: johannesjh) on pypi, that would be great, thank you.
