### ISSUE TITLE
How to disable warnings and DEBUG output

### ISSUE THREAD

**Issue by sprnza** [beancount/smart_importer#53]
Hi there! Thanks for the awesome project.
I've got a little question.
How could I disable this output with python 3.7?

```
/usr/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
DEBUG:smart_importer.decorator_baseclass:The Decorator was applied to a class.                                                   
DEBUG:smart_importer.decorator_baseclass:The Decorator was applied to a class.
```

Thanks!

**Comment by johannesjh** [comment]
Hi! 

Thank you for pointing this out! 

Regarding the smart_importer debug output: I think I have not set up logging properly, and I can change that. What I found out so far:

1. how logging should be set up in the smart_importer module:

> Modules should not be calling logging.basicConfig. Only the main program should call basicConfig once, if at all. (from https://stackoverflow.com/questions/26086968/overwriting-python-log-config)

> When developing a library which uses logging, you should take care to document how the library uses logging - for example, the names of loggers used.
> (from https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library)


2. how the log level can be changed from outside (e.g., when using or debugging a smart_importer decorator):

> You need to call setLevel on your Logger instance.
> 
> LOGGER = logging.getLogger('your.module.file.name')
> LOGGER.setLevel(_level)
> LOGGER.info('foo')
> (from https://stackoverflow.com/questions/10151698/change-level-of-python-fileconfig-logger)

> yaml based config 
> (from https://stackoverflow.com/a/38538348)

Regarding scikit-learn's deprecation warnings: Looks like these warnings come from deep inside scikit-learn's source code. Specifically, `sklearn/feature_extraction/text.py` line 17 contains this import statement: `from collections import Mapping, defaultdict` ...and I don't think smart_importer can do anything about it. 
=> Can you report this issue to scikit-learn please, if it has not been reported already?

**Comment by johannesjh** [comment]
Pull request #54 will allow you to configure log levels from outside. (And will use python's default log level WARN by default).

**Comment by johannesjh** [comment]
One deprecation warning seems to come from `smart_importer`. 
I created follow-up ticket #55 for it.
