### ISSUE TITLE
Communicate more clearly that this project does not provide importers, but that it helps make existing importers smarter

### ISSUE THREAD

**Issue by yagebu** [beancount/smart_importer#56]
It's not really "smart", is it? Is there maybe a better name we could give it?

**Comment by johannesjh** [comment]
I liked "smart" as part of the name because that's how machine learning is often marketed. Artificial intelligence uses the same metaphor. But we can certainly talk about choosing a better name. Any ideas or suggestions?

**Comment by yagebu** [comment]
I can't really think of any name right now that's as concise and sounds as good.

Maybe keeping the name is not so bad, but the description should be updated - this package doesn't provide any importers, rather it provides helpers to turn any existing importer into a "smart importer"

**Comment by johannesjh** [comment]
ok, I'll rephrase the ticket accordingly.
