### ISSUE TITLE
Code standards

### ISSUE THREAD

**Issue by yagebu** [beancount/smart_importer#57]
So far the code doesn't really follow any code standards and is (in parts) horrible to read. It should at least pass something like flake8 and ideally also pylint.

**Comment by johannesjh** [comment]
@yagebu Hi, thank you for reviewing the code and thank you very much for your improvements!

**Comment by yagebu** [comment]
I've added a job to travis that runs flake8 and pylint (in #60). It's allowed to fail for now, but any help to shrink the list of warnings and improve the codebase are welcome ;)
