### ISSUE TITLE
Canonical usage

### ISSUE THREAD

**Issue by yagebu** [beancount/smart_importer#59]
The currently recommended way to use this is quite ugly:

    @PredictPostings()
    class SmartMyBankImporter(MyImporter):
        pass

Why even have the decorators, if they're not intended to be used as such?

**Comment by johannesjh** [comment]
It has a reason why, but I agree that it is rather ugly now.

I originally wanted to apply the decorator straight to the importer class, like so:

```python3
@PredictPostings()
class MyBankImporter(ImporterProtocol):
    ...
```

but then I found that decorated importers made regression testing difficult, hence the recommendation to keep a reference of the undecorated importer.

Any suggestions, what would be a nicer solution? Should we make it a function call, like so:

```python3
class MyBankImporter(ImporterProtocol):
    ...

SmartMyBankImporter = PredictPostings(MyBankImporter)
```

**Comment by yagebu** [comment]
I see. I like the decorators, in particular since they make for nicer chaining of the two "smart importers". Maybe we can expose the original class somehow. Or, if no training data is passed to the decorator, regression testing should also be possible, right?

**Comment by johannesjh** [comment]
> if no training data is passed to the decorator, regression testing should also be possible, right?

yes, I think so.

**Comment by johannesjh** [comment]
I like the idea. I agree that the current way that decorators work is problematic. I think your proposed change would also solve #77.

**Comment by tarioch** [comment]
Really like the idea as well, also matches the way I use smart importer.

**Comment by yagebu** [comment]
#78  is merged
