### ISSUE TITLE
Add duplicate detection functionality

### ISSUE THREAD

**Issue by tarioch** [beancount/smart_importer#75]
I'm currently looking at fava again for handling my import process.
What I noticed is that the duplicate detection logic of bean-extract is not present when importers are used through fava.
I think it should be quite simple to create interceptors similar to the PredictPosting that

1) provides the same functionality as bean-extract (key logic for this is already reusable, so should be very simple)
2) detects duplicates by using a specific metadata key with a reference nr (another use case I have in some cases)

What do you think, should I add them to smart_importer or keep them separate?

**Comment by johannesjh** [comment]
I think I don't understand the problem, can you elaborate please. 

From what I remember, I think that fava does (or did in the past?) include duplicate checks: I remember duplicates being shown in fava's import GUI in a pale green color, with radio buttons on the right-hand side to manually set the status (duplicate or not). I think the duplicate check worked with and without smart_importers. 

Did fava maybe include bean-extract's duplicate checking functionality in order to expose it in the import GUI in a usable way? I am just guessing here, but it may be worth investigation prior to creating a new solution.

**Comment by tarioch** [comment]
If I add the meta __duplicate__ then it will show up as duplicate but the default algorithm that bean-extract uses is not in place (basically detect similar transactions). What I now did was create a decorator which does exactly this, add the __duplicate__ meta. @yagebu maybe you have some better insights.

**Comment by tarioch** [comment]
See my changes here https://github.com/beancount/smart_importer/compare/feature/duplicates which make this work very nicely with fava.
I'm using the default algorithm in most cases and a different comparator (based on a reference id) in another case and both work perfectly fine with fava now.

**Comment by tarioch** [comment]
Any further thoughts about this? I'm currently using this and works really well with fava. If you think it's not useful for someone else I'll move it to my personal repo.

**Comment by mondjef** [comment]
could this same approach be used to provide fava with the __source__ metadata key?

**Comment by tarioch** [comment]
Normally I'm setting source metadata directly in the importer as this is custom to each importer.

**Comment by tarioch** [comment]
Actually extract_from_file does not call the duplicate detection logic, only extract (and as you wrote fava calls extract_from_file not extract). So that's what the DuplicateDetector does, it calls that logic and then sets the `__duplicate__` meta data so it will be correctly displayed in fava.

The thing that `DuplicateDetector` supports is it allows to customize the comparison function (the `DuplicateDetector` is only a simple wrapper to instantiate/configure the core beancount logic)

**Comment by yagebu** [comment]
@tarioch: Sorry for not commenting any earlier. On first glance I like it - when restructuring the decorators, I was hoping that it would enable this kind of application.

Maybe the class could already take arguments to allow for some basic cases of "custom" duplicate detection (i.e. by a meta key). Right now it just provides the same duplicate detection that Beancount provides, right?

**Comment by tarioch** [comment]
Yes it's just reusing the logic from Beancount. The good thing is that this logic was already made configurable. So for the comparison using the key my implementation is simply

```python
class ReferenceDuplicatesComparator:
    def __call__(self, entry1, entry2):
        return 'ref' in entry1.meta and 'ref' in entry2.meta and entry1.meta['ref'] == entry2.meta['ref']

MyImporter = DuplicateDetector(comparator=ReferenceDuplicatesComparator())(OriginalImporter)
```

**Comment by johannesjh** [comment]
Ok, I suggest let's merge this. It adds extra configurability and it showcases another usecase for the decorators. Thank you @tarioch

**Comment by Ramblurr** [comment]
It would be great to see an example of how to use this.

I have a bog standard importer and want to add duplicate check functionality when importing through fava.

**Comment by tarioch** [comment]
I have two use cases that I'm using this.

In my import config I do

Duplicate detection using the default logic of beancount (compares things like dates, accounts, ...)
```
from myimporter import MyImporter
from smart_importer import apply_hooks, PredictPostings
from smart_importer.detector import DuplicateDetector

CONFIG = [
     apply_hooks(MyImporter(), [DuplicateDetector()]),
]
```


Duplicate detection using the my own logic (using a reference number I store in the metadata)
```
from myimporter import MyImporter
from smart_importer import apply_hooks, PredictPostings
from smart_importer.detector import DuplicateDetector

class ReferenceDuplicatesComparator:
    def __call__(self, entry1, entry2):
        return 'ref' in entry1.meta and 'ref' in entry2.meta and entry1.meta['ref'] == entry2.meta['ref']

CONFIG = [
     apply_hooks(MyImporter(), [DuplicateDetector(comparator=ReferenceDuplicatesComparator)]),
]
```

**Comment by Ramblurr** [comment]
Thanks @tarioch, comparing ref meta data is a great idea.

If i want to use both `ReferenceDuplicatesComparator` and the default behavior of `DuplicateDetector`, should i pass two instances of `DuplicateDetector`?
That is, something like:
```python
from myimporter import MyImporter
from smart_importer import apply_hooks, PredictPostings
from smart_importer.detector import DuplicateDetector

class ReferenceDuplicatesComparator:
    def __call__(self, entry1, entry2):
        return 'ref' in entry1.meta and 'ref' in entry2.meta and entry1.meta['ref'] == entry2.meta['ref']

CONFIG = [
     apply_hooks(MyImporter(), [DuplicateDetector(), DuplicateDetector(comparator=ReferenceDuplicatesComparator)]),
]
```

**Comment by tarioch** [comment]
Yes, that will work. In the end all the duplicate dector does is set a special metadata key called '__duplicate__' to True, this is read both by fava as well as the standard beancount utils.
