### ISSUE TITLE
test failure due to invalid syntax

### ISSUE THREAD

**Issue by tbm** [beancount/smart_importer#81]
The tests fail due to:
```
E     File "/home/tbm/scratch/cvs/smart_importer/smart_importer/predictor.py", line 74
E       f"After filtering for account {self.account}, "
E                                                     ^
E   SyntaxError: invalid syntax
```

This makes it work but I'm not sure what the correct fix is:

```
-                f"After filtering for account {self.account}, "
-                f"the training data consists of {len(training_data)} entries.")
+                "After filtering for account {self.account}, "
+                "the training data consists of {len(training_data)} entries.")
```

@yagebu

**Comment by yagebu** [comment]
This package requires Python 3.6, are you running on 3.5?

**Comment by tbm** [comment]
> This package requires Python 3.6, are you running on 3.5?

Yes, thanks.

**Comment by yagebu** [comment]
And now it shouldn't require 3.5 anymore ;)

**Comment by tbm** [comment]
* Jakob Schnitzer <notifications@github.com> [2018-12-20 13:03]:
> And now it shouldn't require 3.5 anymore ;)

Yep, 'make check' works fine now.

'make lint' gives me dependency problems:

Collecting black
  Could not find a version that satisfies the requirement black (from versions: )
No matching distribution found for black

-- 
Martin Michlmayr
https://www.cyrius.com/

**Comment by yagebu** [comment]
Well apparently black doesn't support 3.5 - upgrade to a more recent Python version for development...
