### ISSUE TITLE
please provide the hook helpers as an own package

### ISSUE THREAD

**Issue by evgeni** [beancount/smart_importer#97]
Hey,

I'd like to use the `apply_hooks` helper (and the `ImporterHook` "interface") from `smart_importer/hooks.py` in my own code, but would prefer to avoid depending on `smart_importer` due to the heavy dependencies it has (numpy, scipy).

Would it be possible to extract those into an own package, or - even better - move them to beancount itself?

Thanks!
Evgeni

**Comment by johannesjh** [comment]
Hi Evgeni, thank you for your interest, and thank you for pointing out beancount's new `filter_function` aka `hook` parameter from https://github.com/beancount/beancount/commit/ba7b4699d136ab02859013331d98b3c5971c841f. I think this is the way to go. Shall we close this issue?
